# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.13.0'
    displayName: 'Install Node.js'

  - task: browserstackcom.browserstack-vsts-extension.browserstack-config-task.BrowserStackConfig@0
    displayName: 'BrowserStack configuration setup.'
    inputs:
      BrowserStackServiceEndPoint: 'Browserstack connection'
      browserstackLocal: true
      bsLocalOptions: '--verbose true --log-file ~/asd.log'


  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
